{{- if and .Values.common.totalInstall .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
    project: {{ .Values.project }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        project: {{ .Values.project }}
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.auth.rootPassword | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.auth.database | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.auth.user | quote }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.auth.password | quote }}
        - name: MYSQL_INITDB_SKIP_TZINFO
          value: {{ .Values.mysql.auth.skipTzinfo | quote }}
        ports:
        - containerPort: {{ .Values.mysql.service.port }}
          name: mysql
        {{- if .Values.mysql.storage.enabled }}
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql
        {{- end }}
{{- end }}